/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadeflota;

import com.mycompany.views.Registro;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    int xMouse, yMouse;
    public Login() {

        initComponents();
 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundMain = new javax.swing.JPanel();
        cerrar = new javax.swing.JPanel();
        cerrartxt = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        nombreEmpresa = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        iniciarSesion = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        separador2 = new javax.swing.JSeparator();
        usuario = new javax.swing.JLabel();
        ingresoUsuario = new javax.swing.JTextField();
        separator1 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        panelEntrar = new javax.swing.JPanel();
        textEntrar = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        tipoPersonaBox = new javax.swing.JComboBox<>();
        tipoPersona = new javax.swing.JLabel();
        noTienesCuentaTxt = new javax.swing.JLabel();
        registrarse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        backgroundMain.setBackground(new java.awt.Color(255, 255, 255));
        backgroundMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backgroundMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundMainMousePressed(evt);
            }
        });
        backgroundMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrar.setBackground(new java.awt.Color(217, 218, 220));
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cerrartxt.setBackground(new java.awt.Color(217, 218, 204));
        cerrartxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cerrartxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrartxt.setText("X");
        cerrartxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrartxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrartxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrartxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrartxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout cerrarLayout = new javax.swing.GroupLayout(cerrar);
        cerrar.setLayout(cerrarLayout);
        cerrarLayout.setHorizontalGroup(
            cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrartxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        cerrarLayout.setVerticalGroup(
            cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrartxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        backgroundMain.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 50, 50));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Sin_títulos-removebg-preview.png"))); // NOI18N
        backgroundMain.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 360, 120));

        nombreEmpresa.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        nombreEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreEmpresa.setText("Syscar");
        backgroundMain.add(nombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 360, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/background.jpg"))); // NOI18N
        background.setText("jLabel1");
        backgroundMain.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 360, 640));

        iniciarSesion.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        iniciarSesion.setText("INICIAR SESION");
        backgroundMain.add(iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 200, -1));

        contraseña.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        contraseña.setText("Contraseña");
        backgroundMain.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        separador2.setBackground(new java.awt.Color(204, 204, 204));
        separador2.setForeground(new java.awt.Color(0, 0, 0));
        backgroundMain.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 360, 20));

        usuario.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        usuario.setText("Usuario");
        backgroundMain.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        ingresoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ingresoUsuario.setForeground(new java.awt.Color(204, 204, 204));
        ingresoUsuario.setText("Ingrese su usuario");
        ingresoUsuario.setBorder(null);
        ingresoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresoUsuarioMousePressed(evt);
            }
        });
        ingresoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoUsuarioActionPerformed(evt);
            }
        });
        backgroundMain.add(ingresoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 350, 30));

        separator1.setBackground(new java.awt.Color(204, 204, 204));
        separator1.setForeground(new java.awt.Color(0, 0, 0));
        backgroundMain.add(separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 360, 20));

        jPasswordField1.setFont(new java.awt.Font("Rage Italic", 0, 24)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setText("********");
        jPasswordField1.setBorder(null);
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordField1MousePressed(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        backgroundMain.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 370, 30));

        panelEntrar.setBackground(new java.awt.Color(153, 153, 153));
        panelEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        textEntrar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        textEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textEntrar.setText("ENTRAR");
        textEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textEntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEntrarLayout = new javax.swing.GroupLayout(panelEntrar);
        panelEntrar.setLayout(panelEntrarLayout);
        panelEntrarLayout.setHorizontalGroup(
            panelEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        panelEntrarLayout.setVerticalGroup(
            panelEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textEntrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        backgroundMain.add(panelEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 140, 40));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        backgroundMain.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 50));

        tipoPersonaBox.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        tipoPersonaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Mecanico", "Administrativo", "Conductor ", "Cliente" }));
        tipoPersonaBox.setToolTipText("");
        tipoPersonaBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tipoPersonaBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tipoPersonaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPersonaBoxActionPerformed(evt);
            }
        });
        backgroundMain.add(tipoPersonaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 360, 30));

        tipoPersona.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        tipoPersona.setText("TIPO DE USUARIO");
        backgroundMain.add(tipoPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 360, 30));

        noTienesCuentaTxt.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        noTienesCuentaTxt.setText("¿No tienes cuenta? ");
        backgroundMain.add(noTienesCuentaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        registrarse.setForeground(new java.awt.Color(0, 51, 153));
        registrarse.setText("Registrate aquí.");
        registrarse.setBorder(null);
        registrarse.setBorderPainted(false);
        registrarse.setContentAreaFilled(false);
        registrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseActionPerformed(evt);
            }
        });
        backgroundMain.add(registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    private void ingresoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoUsuarioActionPerformed
        //TODO add your handing code here:
    }//GEN-LAST:event_ingresoUsuarioActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void backgroundMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMainMousePressed
        
    }//GEN-LAST:event_backgroundMainMousePressed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void cerrartxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrartxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrartxtMouseClicked

    private void cerrartxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrartxtMouseEntered
        cerrar.setBackground(Color.red);
        cerrartxt.setForeground(Color.white);
    }//GEN-LAST:event_cerrartxtMouseEntered

    private void cerrartxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrartxtMouseExited
        cerrar.setBackground(new Color(217,218,220));
        cerrartxt.setForeground(Color.black);
    }//GEN-LAST:event_cerrartxtMouseExited

    private void textEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEntrarMouseEntered
        panelEntrar.setBackground(new Color(183,183,183));
    }//GEN-LAST:event_textEntrarMouseEntered

    private void textEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEntrarMouseExited
        panelEntrar.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_textEntrarMouseExited

    private void ingresoUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresoUsuarioMousePressed
        if (ingresoUsuario.getText().equals("Ingrese su usuario")){
            ingresoUsuario.setText("");
            ingresoUsuario.setForeground(Color.black);
        }
        if (String.valueOf(jPasswordField1.getPassword()).isEmpty()){
            jPasswordField1.setText("********");
            jPasswordField1.setForeground(new Color(204,204,204));
        }
       
        
    }//GEN-LAST:event_ingresoUsuarioMousePressed

    private void jPasswordField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MousePressed
        if (String.valueOf(jPasswordField1.getPassword()).equals("********")){
            jPasswordField1.setText("");
            jPasswordField1.setForeground(Color.black);
        }
        if (ingresoUsuario.getText().isEmpty()){
            ingresoUsuario.setText("Ingrese su usuario");
            ingresoUsuario.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_jPasswordField1MousePressed

    private void tipoPersonaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPersonaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoPersonaBoxActionPerformed

    private void registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseActionPerformed
        JFrame registroFrame = new JFrame("Registro");
        Registro registroPanel = new Registro();
        registroFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        registroFrame.getContentPane().add(registroPanel);
        registroFrame.pack(); // Ajusta el tamaño del frame al contenido
        registroFrame.setLocationRelativeTo(null); // Centra la ventana
        registroFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrarseActionPerformed
    

     /* @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel backgroundMain;
    private javax.swing.JPanel cerrar;
    private javax.swing.JLabel cerrartxt;
    private javax.swing.JLabel contraseña;
    private javax.swing.JPanel header;
    private javax.swing.JTextField ingresoUsuario;
    private javax.swing.JLabel iniciarSesion;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel noTienesCuentaTxt;
    private javax.swing.JLabel nombreEmpresa;
    private javax.swing.JPanel panelEntrar;
    private javax.swing.JButton registrarse;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separator1;
    private javax.swing.JLabel textEntrar;
    private javax.swing.JLabel tipoPersona;
    private javax.swing.JComboBox<String> tipoPersonaBox;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables

  
}
