/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views.Gerente;

/**
 *
 * @author USUARIO
 */
public class Gerente extends javax.swing.JPanel {

    /**
     * Creates new form Gerente
     */
    public Gerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menuGerente = new javax.swing.JPanel();
        menuGerenteTxt = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        metricasPrincipales = new javax.swing.JPanel();
        metricasPrincipalesTxt = new javax.swing.JLabel();
        generarInformes = new javax.swing.JPanel();
        generarInformesTxt = new javax.swing.JLabel();
        estadoFlota = new javax.swing.JPanel();
        estadoFlotaTxt = new javax.swing.JLabel();
        herramientas = new javax.swing.JPanel();
        herramientasTxt = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(255, 255, 255));

        menuGerenteTxt.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        menuGerenteTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuGerenteTxt.setText("menu");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        metricasPrincipales.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        metricasPrincipalesTxt.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        metricasPrincipalesTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        metricasPrincipalesTxt.setText("metricas principales");

        javax.swing.GroupLayout metricasPrincipalesLayout = new javax.swing.GroupLayout(metricasPrincipales);
        metricasPrincipales.setLayout(metricasPrincipalesLayout);
        metricasPrincipalesLayout.setHorizontalGroup(
            metricasPrincipalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(metricasPrincipalesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        metricasPrincipalesLayout.setVerticalGroup(
            metricasPrincipalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(metricasPrincipalesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        generarInformes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        generarInformesTxt.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        generarInformesTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generarInformesTxt.setText("generar informes");

        javax.swing.GroupLayout generarInformesLayout = new javax.swing.GroupLayout(generarInformes);
        generarInformes.setLayout(generarInformesLayout);
        generarInformesLayout.setHorizontalGroup(
            generarInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(generarInformesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        generarInformesLayout.setVerticalGroup(
            generarInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(generarInformesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        estadoFlota.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        estadoFlotaTxt.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        estadoFlotaTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estadoFlotaTxt.setText("estado de la flota");

        javax.swing.GroupLayout estadoFlotaLayout = new javax.swing.GroupLayout(estadoFlota);
        estadoFlota.setLayout(estadoFlotaLayout);
        estadoFlotaLayout.setHorizontalGroup(
            estadoFlotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(estadoFlotaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        estadoFlotaLayout.setVerticalGroup(
            estadoFlotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(estadoFlotaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        herramientas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        herramientasTxt.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        herramientasTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        herramientasTxt.setText("herramientas");

        javax.swing.GroupLayout herramientasLayout = new javax.swing.GroupLayout(herramientas);
        herramientas.setLayout(herramientasLayout);
        herramientasLayout.setHorizontalGroup(
            herramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(herramientasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        herramientasLayout.setVerticalGroup(
            herramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(herramientasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menuGerenteLayout = new javax.swing.GroupLayout(menuGerente);
        menuGerente.setLayout(menuGerenteLayout);
        menuGerenteLayout.setHorizontalGroup(
            menuGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuGerenteTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuGerenteLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addComponent(metricasPrincipales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(generarInformes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(estadoFlota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(herramientas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuGerenteLayout.setVerticalGroup(
            menuGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuGerenteLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(menuGerenteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(metricasPrincipales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generarInformes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estadoFlota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(herramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menuGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 720, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel estadoFlota;
    private javax.swing.JLabel estadoFlotaTxt;
    private javax.swing.JPanel generarInformes;
    private javax.swing.JLabel generarInformesTxt;
    private javax.swing.JPanel herramientas;
    private javax.swing.JLabel herramientasTxt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menuGerente;
    private javax.swing.JLabel menuGerenteTxt;
    private javax.swing.JPanel metricasPrincipales;
    private javax.swing.JLabel metricasPrincipalesTxt;
    // End of variables declaration//GEN-END:variables
}
