/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

/**
 *
 * @author USUARIO
 */
public class Registro extends javax.swing.JPanel {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGround = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        nombreEmpresa = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        registro = new javax.swing.JLabel();
        registroApellido = new javax.swing.JLabel();
        registroApellidoTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        registroTelefono = new javax.swing.JLabel();
        registroTelefonoTxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        registroContraseña = new javax.swing.JLabel();
        registroContraseñaTxt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        tipoPersonaBox = new javax.swing.JComboBox<>();
        tipoPersona = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        registroNombre = new javax.swing.JLabel();
        registroNombreTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        registroIdentificacion = new javax.swing.JLabel();
        registroIdentificacionTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        registroNombreUsuario = new javax.swing.JLabel();
        registroNombreUsuarioTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        backGround.setBackground(new java.awt.Color(255, 255, 255));
        backGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Sin_títulos-removebg-preview.png"))); // NOI18N
        backGround.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 360, 120));

        nombreEmpresa.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        nombreEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreEmpresa.setText("Syscar");
        backGround.add(nombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 360, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/background.jpg"))); // NOI18N
        background.setText("jLabel1");
        backGround.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 360, 640));

        registro.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        registro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registro.setText("REGISTRO");
        backGround.add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 660, -1));

        registroApellido.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        registroApellido.setText("apellidos");
        backGround.add(registroApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        registroApellidoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registroApellidoTxt.setForeground(new java.awt.Color(204, 204, 204));
        registroApellidoTxt.setText("Ingrese sus apellidos");
        registroApellidoTxt.setBorder(null);
        registroApellidoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroApellidoTxtActionPerformed(evt);
            }
        });
        backGround.add(registroApellidoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 300, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        backGround.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 290, 20));

        registroTelefono.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        registroTelefono.setText("telefono");
        backGround.add(registroTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        registroTelefonoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registroTelefonoTxt.setForeground(new java.awt.Color(204, 204, 204));
        registroTelefonoTxt.setText("Ingrese su telefono");
        registroTelefonoTxt.setBorder(null);
        registroTelefonoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroTelefonoTxtActionPerformed(evt);
            }
        });
        backGround.add(registroTelefonoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 260, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        backGround.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 210, 40));

        registroContraseña.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        registroContraseña.setText("contraseña");
        backGround.add(registroContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        registroContraseñaTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registroContraseñaTxt.setForeground(new java.awt.Color(204, 204, 204));
        registroContraseñaTxt.setText("Ingrese su contraseña");
        registroContraseñaTxt.setBorder(null);
        registroContraseñaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroContraseñaTxtActionPerformed(evt);
            }
        });
        backGround.add(registroContraseñaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 270, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        backGround.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 280, 10));

        tipoPersonaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Gerente", "Administrativo", "Conductor", "Mecanico", " " }));
        tipoPersonaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPersonaBoxActionPerformed(evt);
            }
        });
        backGround.add(tipoPersonaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 380, 30));

        tipoPersona.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        tipoPersona.setText("TIPO DE PERSONA");
        backGround.add(tipoPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        backGround.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 20, 300));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 220, 10));

        registroNombre.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        registroNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registroNombre.setText("NOMBRE");
        jPanel1.add(registroNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 20, 300, -1));

        registroNombreTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registroNombreTxt.setForeground(new java.awt.Color(204, 204, 204));
        registroNombreTxt.setText("Ingrese su nombre");
        registroNombreTxt.setBorder(null);
        registroNombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroNombreTxtActionPerformed(evt);
            }
        });
        jPanel1.add(registroNombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 300, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 280, 20));

        registroIdentificacion.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        registroIdentificacion.setText("identificacion");
        jPanel1.add(registroIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        registroIdentificacionTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registroIdentificacionTxt.setForeground(new java.awt.Color(204, 204, 204));
        registroIdentificacionTxt.setText("Ingrese su identificacion");
        registroIdentificacionTxt.setBorder(null);
        registroIdentificacionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroIdentificacionTxtActionPerformed(evt);
            }
        });
        jPanel1.add(registroIdentificacionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 200, 10));

        registroNombreUsuario.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        registroNombreUsuario.setText("Nombre de usuario");
        jPanel1.add(registroNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 30));

        registroNombreUsuarioTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registroNombreUsuarioTxt.setForeground(new java.awt.Color(204, 204, 204));
        registroNombreUsuarioTxt.setText("Ingrese su nombre de usuario");
        registroNombreUsuarioTxt.setBorder(null);
        registroNombreUsuarioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroNombreUsuarioTxtActionPerformed(evt);
            }
        });
        jPanel1.add(registroNombreUsuarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 240, 30));

        backGround.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 300, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registroNombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroNombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroNombreTxtActionPerformed

    private void registroApellidoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroApellidoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroApellidoTxtActionPerformed

    private void registroIdentificacionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroIdentificacionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroIdentificacionTxtActionPerformed

    private void registroTelefonoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroTelefonoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroTelefonoTxtActionPerformed

    private void registroNombreUsuarioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroNombreUsuarioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroNombreUsuarioTxtActionPerformed

    private void registroContraseñaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroContraseñaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroContraseñaTxtActionPerformed

    private void tipoPersonaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPersonaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoPersonaBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backGround;
    private javax.swing.JLabel background;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nombreEmpresa;
    private javax.swing.JLabel registro;
    private javax.swing.JLabel registroApellido;
    private javax.swing.JTextField registroApellidoTxt;
    private javax.swing.JLabel registroContraseña;
    private javax.swing.JTextField registroContraseñaTxt;
    private javax.swing.JLabel registroIdentificacion;
    private javax.swing.JTextField registroIdentificacionTxt;
    private javax.swing.JLabel registroNombre;
    private javax.swing.JTextField registroNombreTxt;
    private javax.swing.JLabel registroNombreUsuario;
    private javax.swing.JTextField registroNombreUsuarioTxt;
    private javax.swing.JLabel registroTelefono;
    private javax.swing.JTextField registroTelefonoTxt;
    private javax.swing.JLabel tipoPersona;
    private javax.swing.JComboBox<String> tipoPersonaBox;
    // End of variables declaration//GEN-END:variables
}
