/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views.Mecanico;

/**
 *
 * @author USUARIO
 */
public class Mecanico extends javax.swing.JPanel {

    /**
     * Creates new form Mecanico
     */
    public Mecanico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menuMecanico = new javax.swing.JPanel();
        menuMecanicoTxt = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        listaVehiculosRevision = new javax.swing.JPanel();
        listaVehiculosRevisionTxt = new javax.swing.JLabel();
        formularioDiagnostico = new javax.swing.JPanel();
        formularioDiagnosticoTxt = new javax.swing.JLabel();
        registroMantenimientos = new javax.swing.JPanel();
        registroMantenimientosTxt = new javax.swing.JLabel();
        historialReparaciones = new javax.swing.JPanel();
        historialReparacionesTxt = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(255, 255, 255));

        menuMecanicoTxt.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        menuMecanicoTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuMecanicoTxt.setText("menu");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        listaVehiculosRevision.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        listaVehiculosRevisionTxt.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        listaVehiculosRevisionTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listaVehiculosRevisionTxt.setText("lista de vehiculos para revision");

        javax.swing.GroupLayout listaVehiculosRevisionLayout = new javax.swing.GroupLayout(listaVehiculosRevision);
        listaVehiculosRevision.setLayout(listaVehiculosRevisionLayout);
        listaVehiculosRevisionLayout.setHorizontalGroup(
            listaVehiculosRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listaVehiculosRevisionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        listaVehiculosRevisionLayout.setVerticalGroup(
            listaVehiculosRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listaVehiculosRevisionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        formularioDiagnostico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        formularioDiagnosticoTxt.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        formularioDiagnosticoTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formularioDiagnosticoTxt.setText("formulario de diagnostico");

        javax.swing.GroupLayout formularioDiagnosticoLayout = new javax.swing.GroupLayout(formularioDiagnostico);
        formularioDiagnostico.setLayout(formularioDiagnosticoLayout);
        formularioDiagnosticoLayout.setHorizontalGroup(
            formularioDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formularioDiagnosticoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        formularioDiagnosticoLayout.setVerticalGroup(
            formularioDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formularioDiagnosticoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        registroMantenimientos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        registroMantenimientosTxt.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        registroMantenimientosTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registroMantenimientosTxt.setText("registro de mantenimientos");

        javax.swing.GroupLayout registroMantenimientosLayout = new javax.swing.GroupLayout(registroMantenimientos);
        registroMantenimientos.setLayout(registroMantenimientosLayout);
        registroMantenimientosLayout.setHorizontalGroup(
            registroMantenimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registroMantenimientosTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        registroMantenimientosLayout.setVerticalGroup(
            registroMantenimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registroMantenimientosTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        historialReparaciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        historialReparacionesTxt.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        historialReparacionesTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        historialReparacionesTxt.setText("historial de reparaciones");

        javax.swing.GroupLayout historialReparacionesLayout = new javax.swing.GroupLayout(historialReparaciones);
        historialReparaciones.setLayout(historialReparacionesLayout);
        historialReparacionesLayout.setHorizontalGroup(
            historialReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(historialReparacionesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        historialReparacionesLayout.setVerticalGroup(
            historialReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(historialReparacionesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menuMecanicoLayout = new javax.swing.GroupLayout(menuMecanico);
        menuMecanico.setLayout(menuMecanicoLayout);
        menuMecanicoLayout.setHorizontalGroup(
            menuMecanicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuMecanicoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listaVehiculosRevision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formularioDiagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuMecanicoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addComponent(registroMantenimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(historialReparaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuMecanicoLayout.setVerticalGroup(
            menuMecanicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuMecanicoLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(menuMecanicoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listaVehiculosRevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formularioDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registroMantenimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historialReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menuMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 720, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuMecanico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel formularioDiagnostico;
    private javax.swing.JLabel formularioDiagnosticoTxt;
    private javax.swing.JPanel historialReparaciones;
    private javax.swing.JLabel historialReparacionesTxt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel listaVehiculosRevision;
    private javax.swing.JLabel listaVehiculosRevisionTxt;
    private javax.swing.JPanel menuMecanico;
    private javax.swing.JLabel menuMecanicoTxt;
    private javax.swing.JPanel registroMantenimientos;
    private javax.swing.JLabel registroMantenimientosTxt;
    // End of variables declaration//GEN-END:variables
}
