/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views.Administrativo;

/**
 *
 * @author USUARIO
 */
public class Administrativo extends javax.swing.JPanel {

    /**
     * Creates new form Administrativo
     */
    public Administrativo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menuAdministrativo = new javax.swing.JPanel();
        menuAdministrativoTxt = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        gestionTareas = new javax.swing.JPanel();
        gestionTareasTxt = new javax.swing.JLabel();
        listadoReportes = new javax.swing.JPanel();
        listadoReportesTxt = new javax.swing.JLabel();
        asignacion = new javax.swing.JPanel();
        asignacionTxt = new javax.swing.JLabel();
        comunicacion = new javax.swing.JPanel();
        comunicacionTxt = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));

        menuAdministrativoTxt.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        menuAdministrativoTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuAdministrativoTxt.setText("MENU");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        gestionTareas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        gestionTareasTxt.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        gestionTareasTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gestionTareasTxt.setText("GESTION DE TAREAS");

        javax.swing.GroupLayout gestionTareasLayout = new javax.swing.GroupLayout(gestionTareas);
        gestionTareas.setLayout(gestionTareasLayout);
        gestionTareasLayout.setHorizontalGroup(
            gestionTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gestionTareasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gestionTareasLayout.setVerticalGroup(
            gestionTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gestionTareasLayout.createSequentialGroup()
                .addComponent(gestionTareasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        listadoReportes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        listadoReportesTxt.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        listadoReportesTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listadoReportesTxt.setText("LISTADO DE REPORTES");

        javax.swing.GroupLayout listadoReportesLayout = new javax.swing.GroupLayout(listadoReportes);
        listadoReportes.setLayout(listadoReportesLayout);
        listadoReportesLayout.setHorizontalGroup(
            listadoReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listadoReportesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        listadoReportesLayout.setVerticalGroup(
            listadoReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listadoReportesTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        asignacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        asignacionTxt.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        asignacionTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asignacionTxt.setText("ASIGNACION");

        javax.swing.GroupLayout asignacionLayout = new javax.swing.GroupLayout(asignacion);
        asignacion.setLayout(asignacionLayout);
        asignacionLayout.setHorizontalGroup(
            asignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignacionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        asignacionLayout.setVerticalGroup(
            asignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignacionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        comunicacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        comunicacionTxt.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        comunicacionTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comunicacionTxt.setText("COMUNICACION");

        javax.swing.GroupLayout comunicacionLayout = new javax.swing.GroupLayout(comunicacion);
        comunicacion.setLayout(comunicacionLayout);
        comunicacionLayout.setHorizontalGroup(
            comunicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comunicacionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        comunicacionLayout.setVerticalGroup(
            comunicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comunicacionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menuAdministrativoLayout = new javax.swing.GroupLayout(menuAdministrativo);
        menuAdministrativo.setLayout(menuAdministrativoLayout);
        menuAdministrativoLayout.setHorizontalGroup(
            menuAdministrativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuAdministrativoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuAdministrativoLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addComponent(gestionTareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listadoReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(asignacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(comunicacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuAdministrativoLayout.setVerticalGroup(
            menuAdministrativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAdministrativoLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(menuAdministrativoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gestionTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listadoReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comunicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menuAdministrativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 719, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuAdministrativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel asignacion;
    private javax.swing.JLabel asignacionTxt;
    private javax.swing.JPanel background;
    private javax.swing.JPanel comunicacion;
    private javax.swing.JLabel comunicacionTxt;
    private javax.swing.JPanel gestionTareas;
    private javax.swing.JLabel gestionTareasTxt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel listadoReportes;
    private javax.swing.JLabel listadoReportesTxt;
    private javax.swing.JPanel menuAdministrativo;
    private javax.swing.JLabel menuAdministrativoTxt;
    // End of variables declaration//GEN-END:variables
}
