/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views.Conductor;

/**
 *
 * @author USUARIO
 */
public class Conductor extends javax.swing.JPanel {

    /**
     * Creates new form Conductor
     */
    public Conductor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menuConductor = new javax.swing.JPanel();
        menuConductorTxt = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        rutasAsignadas = new javax.swing.JPanel();
        rutasAsignadasTxt = new javax.swing.JLabel();
        iniciarRuta = new javax.swing.JPanel();
        iniciarRutaTxt = new javax.swing.JLabel();
        registroIncidencia = new javax.swing.JPanel();
        registroIncidenciaTxt = new javax.swing.JLabel();
        informacionVehiculo = new javax.swing.JPanel();
        informacionVehiculoTxt = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuConductorTxt.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        menuConductorTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuConductorTxt.setText("MENU");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        rutasAsignadas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rutasAsignadas.setForeground(new java.awt.Color(153, 153, 153));

        rutasAsignadasTxt.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        rutasAsignadasTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rutasAsignadasTxt.setText("Vista de rutas asignadas");

        javax.swing.GroupLayout rutasAsignadasLayout = new javax.swing.GroupLayout(rutasAsignadas);
        rutasAsignadas.setLayout(rutasAsignadasLayout);
        rutasAsignadasLayout.setHorizontalGroup(
            rutasAsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rutasAsignadasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        rutasAsignadasLayout.setVerticalGroup(
            rutasAsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rutasAsignadasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        iniciarRuta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        iniciarRuta.setForeground(new java.awt.Color(153, 153, 153));

        iniciarRutaTxt.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        iniciarRutaTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iniciarRutaTxt.setText("INICIAR RUTA");

        javax.swing.GroupLayout iniciarRutaLayout = new javax.swing.GroupLayout(iniciarRuta);
        iniciarRuta.setLayout(iniciarRutaLayout);
        iniciarRutaLayout.setHorizontalGroup(
            iniciarRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iniciarRutaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        iniciarRutaLayout.setVerticalGroup(
            iniciarRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iniciarRutaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        registroIncidencia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        registroIncidenciaTxt.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        registroIncidenciaTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registroIncidenciaTxt.setText("REGISTRO DE INCIDENCIA");

        javax.swing.GroupLayout registroIncidenciaLayout = new javax.swing.GroupLayout(registroIncidencia);
        registroIncidencia.setLayout(registroIncidenciaLayout);
        registroIncidenciaLayout.setHorizontalGroup(
            registroIncidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registroIncidenciaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        registroIncidenciaLayout.setVerticalGroup(
            registroIncidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroIncidenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registroIncidenciaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
        );

        informacionVehiculo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        informacionVehiculoTxt.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        informacionVehiculoTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        informacionVehiculoTxt.setText("INFORMACION DE VEHICULO ASIGNADO");

        javax.swing.GroupLayout informacionVehiculoLayout = new javax.swing.GroupLayout(informacionVehiculo);
        informacionVehiculo.setLayout(informacionVehiculoLayout);
        informacionVehiculoLayout.setHorizontalGroup(
            informacionVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(informacionVehiculoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );
        informacionVehiculoLayout.setVerticalGroup(
            informacionVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(informacionVehiculoTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menuConductorLayout = new javax.swing.GroupLayout(menuConductor);
        menuConductor.setLayout(menuConductorLayout);
        menuConductorLayout.setHorizontalGroup(
            menuConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuConductorTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuConductorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addComponent(rutasAsignadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(iniciarRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(registroIncidencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(informacionVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuConductorLayout.setVerticalGroup(
            menuConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuConductorLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(menuConductorTxt)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rutasAsignadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iniciarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registroIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informacionVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(464, Short.MAX_VALUE))
        );

        background.add(menuConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel informacionVehiculo;
    private javax.swing.JLabel informacionVehiculoTxt;
    private javax.swing.JPanel iniciarRuta;
    private javax.swing.JLabel iniciarRutaTxt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menuConductor;
    private javax.swing.JLabel menuConductorTxt;
    private javax.swing.JPanel registroIncidencia;
    private javax.swing.JLabel registroIncidenciaTxt;
    private javax.swing.JPanel rutasAsignadas;
    private javax.swing.JLabel rutasAsignadasTxt;
    // End of variables declaration//GEN-END:variables
}
